In [4]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [3]:
pd.set_option("mode.copy_on_write", True)

C:\Users\lemur\AppData\Local\Temp\ipykernel_24676\263416689.py:1: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.set_option("mode.copy_on_write", True)

In [24]:
%%timeit
dane = {}
for c in range(50):
    dane[f"column_{c}"] = np.random.normal(100, 40, size=1000)

1.11 ms ± 27.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [6]:
df = pd.DataFrame(dane)

In [18]:
print(df)

       column_0    column_1    column_2    column_3    column_4    column_5  \
0    103.666076   76.377011   23.438115  102.697528   91.713807  207.805833
1     67.938142  178.883811  173.012086   49.150938  102.468401   72.849438
2    135.577592  151.855618  144.372770   69.035938  131.901697   75.077873
3     99.411590  144.588472   76.955423  118.908247  104.790112  172.698604
4    108.016693  110.350922   66.826235   31.873118  167.123797   95.711428
..          ...         ...         ...         ...         ...         ...
995  152.907083  129.880331  111.599006  129.562637  147.539086  127.922247
996   86.589278   66.792369  103.981791   56.403272   32.884451  132.414945
997  122.645165  101.528783  173.183505   71.967456  175.956716   96.356982
998  117.164572  146.276696   77.782162   43.871615   52.999472  139.456560
999  123.710399   59.392877  -54.971917   94.094274   51.499348   53.254032

       column_6    column_7    column_8    column_9   column_10   column_11  \
0    125.812278   97.770207   83.326686  135.084268  121.893869  101.519058
1     25.165372   65.829830  118.943344   44.071478  126.480018   30.738445
2     61.671775   42.727508  131.196407  108.440717  135.997606   94.723721
3     77.135548  116.279747   96.644123  160.953391   76.139319  100.382447
4     41.507779   96.752075   94.768358  177.243494   91.623575  160.302547
..          ...         ...         ...         ...         ...         ...
995   43.903298  104.284346   57.032295  191.349366   51.722332  105.747633
996  128.963406  118.469478  205.849272  108.258048   67.988752  136.331843
997  133.316516   72.883619  -23.375234  170.552253   76.056998  102.790579
998   62.899844  124.327149   79.525930   23.131071  160.240419  150.805497
999  111.712900  136.679484  101.920722  127.575979   86.805455   74.921263

      column_12   column_13   column_14   column_15   column_16   column_17  \
0     66.842781  135.574146  117.354094   84.562271  125.367975  165.488356
1    106.218700   89.346264   72.765611  108.199344  128.658493  130.592302
2     93.261415  136.485498  157.934829   91.513651   62.371415   95.293992
3     98.541741   53.225879   86.439997   87.370403   76.102993  118.905713
4    141.231654  115.301621  124.406207   13.806760  129.002752   90.303785
..          ...         ...         ...         ...         ...         ...
995   80.834472   55.428449   92.677806   91.137041  128.735769   93.897739
996   47.903939  123.959754    4.327479   98.215951   83.988012   79.801055
997  108.720328   70.622551  150.303367  107.291626  107.559547  150.601067
998   51.762846  114.578144  157.974315   77.937539   77.396570  141.758599
999  102.558493   73.688682  145.418257   81.161983   73.383055   97.241706

      column_18   column_19   column_20   column_21   column_22   column_23  \
0     58.244105  107.704579  138.324131   95.920916   38.432546  128.475175
1    125.182505   77.119324   75.084277  102.711261  116.437000   54.851355
2     52.545833   52.238747   87.938285   98.696257   48.100778   74.509923
3     96.306003  114.745867  118.541313  122.643446  170.132567  155.300831
4    112.301792   26.522365   90.358657   49.857172  109.396715   56.447152
..          ...         ...         ...         ...         ...         ...
995   94.237037   57.289885   86.163997   86.985009  138.248355   81.542434
996  211.306109  107.110534   77.031959  105.196570  176.133141   83.222824
997   93.602621  100.835178   93.369504   88.485820   74.985533   95.055322
998  171.639101  129.075146  105.458032  103.101251   93.328754   88.695955
999  170.959809  147.475951  105.267940  111.038049   55.724771   98.761392

      column_24   column_25   column_26   column_27   column_28   column_29  \
0    187.156504   95.015817  121.916746   23.608960  118.993657  101.683956
1     63.481449  116.288609  145.156917  125.936316   80.725896   72.992565
2    143.834906  150.229310   98.961818   88.068768  119.144507  153.140068
3    159.505787  142.018501  125.246390  163.098423  103.148793   47.498612
4     24.525235  136.945936  125.233735   82.510580  116.740753   76.409240
..          ...         ...         ...         ...         ...         ...
995  126.326618   49.956039  145.659779   99.400136  111.956898   54.419962
996  141.550858  112.464780  144.178496  111.929002  152.238345  181.563696
997  110.322203  149.552101   53.641775  100.128905   98.876476  118.359270
998  125.266920   68.324540   48.027740  100.530530  135.628991   34.900595
999   81.397404  128.444449   49.761236  158.290000   76.737455  151.170907

      column_30   column_31   column_32   column_33   column_34   column_35  \
0    118.563630  121.255788   80.282603  109.201410   84.992759    4.110182
1    104.828674   73.113631  138.948638   72.189521   70.116612   80.397483
2    124.465216   78.534897  109.856158   67.092398  181.415705   87.989471
3     86.935061   82.022945   88.400420   22.253198   38.505302  114.396126
4    114.287568  166.580595   22.332528  194.904432  140.721322  103.420783
..          ...         ...         ...         ...         ...         ...
995  177.260294   77.083299  143.226312   89.568924   34.279626   84.940035
996   84.910539   93.612136   54.465152   85.158104  116.596318  129.465891
997   64.036282  112.048615  118.591634   32.982290  220.623885   33.717454
998  127.609665  182.758224  116.959442  189.651761  102.991573   84.710579
999   30.376453   87.798233   96.032321   63.561570  113.234412  133.603815

      column_36   column_37   column_38   column_39   column_40   column_41  \
0     85.940173   75.678603  116.082539   62.616875   83.624448   92.936975
1     85.316993  101.479628  205.953675   90.217733    4.794538  116.658028
2     83.322385  143.901229  100.254425   24.026974   95.176244   45.015967
3     29.576128  140.161531   98.716202  131.940672   28.094326   56.410290
4     56.624253  107.727862   98.631150   92.753508   43.653813  163.170474
..          ...         ...         ...         ...         ...         ...
995  119.804497   85.822805   72.730018  122.689153   73.932252   92.407583
996   92.724573   84.364117   76.333842  105.043802   39.080515   58.225994
997   58.762561   46.199292  178.709651   65.112104   75.432584   79.510556
998  141.307187  117.705217  128.481877   51.549246  126.775237  124.566804
999   73.886457   85.056461   71.836799  124.901667   93.604232  184.975305

      column_42   column_43   column_44   column_45   column_46   column_47  \
0    129.743154   76.605517  152.537341  105.687397  183.154904  134.964740
1     99.848336   88.747957  123.028365  182.468692   72.935982   96.323414
2    157.853054   97.187348   56.577946  120.707820   94.952192   73.884861
3    132.333435  113.990951  100.757806  110.123222  136.308212   97.968492
4     21.146035   29.634361  111.530405   86.255339  197.036666  155.745555
..          ...         ...         ...         ...         ...         ...
995   89.540385   86.276450  133.925925  124.154286   62.167734   75.648414
996  132.570059  112.590408    3.415628   71.616177  164.471181   71.014437
997  187.848923   56.718140  100.782947  120.815068  137.875813  174.035629
998   95.962940   61.774220   46.985803  103.598559   88.168626   46.931391
999  119.928133  138.348992  102.217560  118.648781   94.509826   91.913349

      column_48   column_49
0    114.508082  125.658894
1    160.932620  148.853845
2     81.592709  131.840098
3    -30.624943  132.249136
4    136.234478  115.073275
..          ...         ...
995  105.673583  159.858851
996   46.280457   18.793680
997  154.519770  120.348090
998  161.770803  111.453550
999  129.377481   81.610896

[1000 rows x 50 columns]

In [20]:
pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 500)

In [17]:
pd.get_option("display.max_rows")

200

In [25]:
# wczytywanie CSV

In [26]:
df = pd.read_csv("test.csv")
df

                          id_klienta;nazwisko;kwota_zakupu;data_rejestracji
101;Kowalski   Jan;1 250                                      50;2024-01-15
102;Nowak      Anna;3 400                                     00;2024-02-20
103;Wiśniewski Piotr;890                                      25;2024-03-05

In [ ]:
# ; jako separator kolumn
df = pd.read_csv("test.csv", sep=';')
df

   id_klienta           nazwisko kwota_zakupu data_rejestracji
0         101      Kowalski, Jan     1 250,50       2024-01-15
1         102        Nowak, Anna     3 400,00       2024-02-20
2         103  Wiśniewski, Piotr       890,25       2024-03-05

In [28]:
df.dtypes

id_klienta          int64
nazwisko              str
kwota_zakupu          str
data_rejestracji      str
dtype: object

In [29]:
# dodajemy , jako separator miejsce dziesiętnych
df = pd.read_csv("test.csv", sep=";", decimal=',')
df

   id_klienta           nazwisko kwota_zakupu data_rejestracji
0         101      Kowalski, Jan     1 250,50       2024-01-15
1         102        Nowak, Anna     3 400,00       2024-02-20
2         103  Wiśniewski, Piotr       890,25       2024-03-05

In [30]:
df.dtypes

id_klienta          int64
nazwisko              str
kwota_zakupu          str
data_rejestracji      str
dtype: object

In [31]:
# dodajemy spację jako rozdzielacz tysięcy
df = pd.read_csv("test.csv", sep=";", decimal=",", thousands=' ')
df

   id_klienta           nazwisko  kwota_zakupu data_rejestracji
0         101      Kowalski, Jan       1250.50       2024-01-15
1         102        Nowak, Anna       3400.00       2024-02-20
2         103  Wiśniewski, Piotr        890.25       2024-03-05

In [32]:
df.dtypes

id_klienta            int64
nazwisko                str
kwota_zakupu        float64
data_rejestracji        str
dtype: object

In [ ]:
df["nazwisko"]...