In [2]:
import pandas as pd

In [3]:
dane = pd.read_csv("spoleczenstwo.csv", sep="|")
dane

,id,imie,nazwisko,firma,email,telefon,miasto,ulica,nr_budynku
0,1,Kacper,Ciuk,Cudzich s.c.,dagmara53@example.net,579 880 315,Legionowo,Zakole,87/88
1,2,Bianka,Dybaś,Kustosz Sp.j.,skomuda@example.net,+48 533 979 087,Oleśnica,Kościuszki,54/17
2,3,Sara,Kubasiak,Stowarzyszenie Czerniec Sp. z o.o.,nycartur@example.org,505 484 908,Nowy Dwór Mazowiecki,Orla,890
3,4,Juliusz,Furga,Grupa Kasperczak s.c.,elzbietabakiewicz@example.com,696 973 561,Biłgoraj,Bankowa,64
4,5,Olaf,Mydlarz,Tolak-Jędrys Sp.k.,apietrusiak@example.com,+48 739 856 809,Lublin,Wierzbowa,925
...,...,...,...,...,...,...,...,...,...
9995,9996,Maciej,Skubała,Grupa Pilipczuk,adrian51@example.com,726 300 145,Września,Wiśniowa,236
9996,9997,Tomasz,Pachuta,Zbroszczyk-Żelazo S.A.,buksaliwia@example.org,798 327 965,Olkusz,Perłowa,222
9997,9998,Kaja,Musiolik,Fundacja Chmielak s.c.,juliusz13@example.net,+48 538 645 366,Nysa,Partyzantów,14/62
9998,9999,Bruno,Armata,Stowarzyszenie Moryc Sp.k.,anastazjajakiel@example.com,+48 783 436 091,Stargard Szczeciński,Kossaka,062
9999,10000,Karol,Gadzała,Potęga-Smardz Sp.k.,justyna97@example.net,732 063 096,Wągrowiec,Sawickiej,954

In [4]:
dane["imie"].value_counts()

imie
Kacper        91
Franciszek    87
Juliusz       86
Maciej        86
Damian        81
              ..
Ernest        51
Julita        51
Adam          51
Gaja          49
Jan           47
Name: count, Length: 153, dtype: int64

In [5]:
dane["nazwisko"].value_counts()

nazwisko
Janisz     9
Władyka    9
Perka      9
Zmuda      9
Wałek      9
          ..
Draus      1
Morys      1
Maćczak    1
Gogacz     1
Fidura     1
Name: count, Length: 3452, dtype: int64

In [10]:
nazwiska = pd.DataFrame(dane["nazwisko"].value_counts()).reset_index(drop=False)
nazwiska

     nazwisko  count
0      Janisz      9
1     Władyka      9
2       Perka      9
3       Zmuda      9
4       Wałek      9
...       ...    ...
3447    Draus      1
3448    Morys      1
3449  Maćczak      1
3450   Gogacz      1
3451   Fidura      1

[3452 rows x 2 columns]

In [11]:
imiona = pd.DataFrame(dane["imie"].value_counts()).reset_index(drop=False)

In [ ]:
# to nadpisze plik!
imiona.to_excel("spoleczensto.xlsx", index=False, sheet_name="imiona")
nazwiska.to_excel("spoleczensto.xlsx", index=False, sheet_name="nazwiska")

In [15]:
with pd.ExcelWriter("spoleczensto_ok.xlsx", engine="openpyxl") as writer:
        dane.to_excel(writer,  index=False, sheet_name="dane_surowe")
        imiona.to_excel(writer, index=False, sheet_name="imiona")
        nazwiska.to_excel(writer, index=False, sheet_name="nazwiska")

In [17]:
dane.to_excel("spoleczensto_full.xlsx", index=False)

In [ ]:
# potrzebny pakiet fastparquet albo pyarrow
# !pip install pyarrow
dane.to_parquet("spoleczensto.parquet", index=False)

In [ ]:
pd.read_parquet(
    "spoleczensto.parquet", columns=["nazwisko", "firma"], filters=[("id", ">", 5000)]
)

      nazwisko                          firma
0          Pik             Spółdzielnia Galek
1        Fidor  FPUH Westfal Sp. z o.o. Sp.k.
2       Wizner   Lenda-Lulek Sp. z o.o. Sp.k.
3         Wika   Grupa Komisarczyk Sp. z o.o.
4        Kobel          Wudarczyk-Bzdęga s.c.
...        ...                            ...
4995   Skubała                Grupa Pilipczuk
4996   Pachuta         Zbroszczyk-Żelazo S.A.
4997  Musiolik         Fundacja Chmielak s.c.
4998    Armata     Stowarzyszenie Moryc Sp.k.
4999   Gadzała            Potęga-Smardz Sp.k.

[5000 rows x 2 columns]