In [2]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("../olimpics.zip")
df

,player_id,Name,Sex,Team,NOC,Year,Season,City,Sport,Event,Medal
0,0,A Dijiang,M,China,CHN,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,No medal
1,1,A Lamusi,M,China,CHN,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,No medal
2,2,Gunnar Aaby,M,Denmark,DEN,1920,Summer,Antwerpen,Football,Football Men's Football,No medal
3,3,Edgar Aabye,M,Denmark/Sweden,DEN,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,26,Cornelia (-strannood),F,Netherlands,NED,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,No medal
...,...,...,...,...,...,...,...,...,...,...,...
252560,4986655,Sefora Ada,F,Equatorial Guinea,GEQ,2024,Summer,Paris,Athletics,Women's 100m,No medal
252561,9460001,Emanuela Liuzzi,F,Italy,ITA,2024,Summer,Paris,Wrestling,Women's Freestyle 50kg,No medal
252562,1972077,Isayah Boers,M,Netherlands,NED,2024,Summer,Paris,Athletics,4 x 400m Relay Mixed,Gold
252563,1899865,Kevin Staut,M,France,FRA,2024,Summer,Paris,Equestrian,Jumping Team,Bronze
252564,1924402,Charlie Carvell,M,Great Britain,GBR,2024,Summer,Paris,Athletics,Men's 4 x 400m Relay,Bronze

In [5]:
df["Year"].describe()

count    252565.000000
mean       1981.743908
std          32.596548
min        1896.000000
25%        1960.000000
50%        1988.000000
75%        2008.000000
max        2024.000000
Name: Year, dtype: float64

In [6]:
df.describe()

          player_id           Year
count  2.525650e+05  252565.000000
mean   2.305499e+05    1981.743908
std    4.289330e+05      32.596548
min    0.000000e+00    1896.000000
25%    5.713700e+04    1960.000000
50%    1.356110e+05    1988.000000
75%    2.118590e+05    2008.000000
max    9.460001e+06    2024.000000

In [ ]:
# ile mamy braków?
df.isnull().sum()

player_id    0
Name         0
Sex          0
Team         0
NOC          0
Year         0
Season       0
City         0
Sport        0
Event        0
Medal        0
dtype: int64

In [9]:
# czy mamy tylko 2 płcie?
df['Sex'].value_counts(dropna=False)

Sex
M    178544
F     74021
Name: count, dtype: int64

In [10]:
# jakie mamy rodzaje medali?
df["Medal"].value_counts(dropna=False)

Medal
No medal    213747
Bronze       13070
Gold         13002
Silver       12746
Name: count, dtype: int64

In [ ]:
# kto był gospodarzem
df["City"].unique()

<ArrowStringArray>
[     'Barcelona',         'London',      'Antwerpen',          'Paris',
    'Los Angeles',       'Helsinki',         'Sydney',        'Atlanta',
      'Stockholm',        'Beijing', 'Rio de Janeiro',         'Athina',
    'Mexico City',         'Munich',          'Seoul',         'Berlin',
      'Melbourne',           'Roma',      'Amsterdam',       'Montreal',
         'Moskva',          'Tokyo',      'St. Louis']
Length: 23, dtype: str

In [16]:
# ilu było gospodarzy
df["City"].nunique()

23

In [17]:
# ile było igrzysk
df["Year"].nunique()

31

In [18]:
# czy same letnie igrzyska?
df['Season'].unique()

<ArrowStringArray>
['Summer']
Length: 1, dtype: str

In [34]:
# równouprawnienie

# rok - licza M - liczba F - % M - % F
df_gender = (
    df.groupby(["Year", "Sex"], as_index=False)
    .size()
    .pivot_table(
        index="Year", columns="Sex", values="size", aggfunc="sum", fill_value=0
    )
    .rename(
        columns={
            "F": "Female_count",
            "M": "Male_count",
        }
    )
).reset_index()
df_gender

Sex  Year  Female_count  Male_count
0    1896             0         380
1    1900            33        1903
2    1904            16        1285
3    1906            11        1722
4    1908            47        3054
5    1912            87        3953
6    1920           134        4158
7    1924           244        4989
8    1928           404        4588
9    1932           347        2622
10   1936           468        6038
11   1948           628        5777
12   1952          1497        6773
13   1956           893        4234
14   1960          1435        6684
15   1964          1348        6354
16   1968          1777        6811
17   1972          2193        8111
18   1976          2172        6469
19   1980          1756        5435
20   1984          2447        7007
21   1988          3543        8494
22   1992          4124        8853
23   1996          5008        8772
24   2000          5431        8390
25   2004          5546        7897
26   2008          5816        7786
27   2012          5815        7105
28   2016          6223        7465
29   2020          7266        7855
30   2024          7312        7580

In [ ]:
df_gender