In [2]:
import pandas as pd
import numpy as np

In [3]:
n = 500_000
miasta = ["Warszawa", "Kraków", "Gdańsk", "Wrocław", "Poznań"]
df_duza = pd.DataFrame(
    {
        "Miasto": np.random.choice(miasta, size=n),
        "Wartosc": np.random.uniform(10, 1000, size=n),
    }
)

In [6]:
df_duza.dtypes

Miasto         str
Wartosc    float64
dtype: object

In [5]:
df_duza.memory_usage(deep=True) / 1024

Index         0.128906
Miasto     7518.833008
Wartosc    3906.250000
dtype: float64

In [7]:
df_duza['Miasto_category'] = df_duza['Miasto'].astype('category')

In [8]:
df_duza

          Miasto     Wartosc Miasto_category
0         Gdańsk  512.420670          Gdańsk
1        Wrocław  911.975903         Wrocław
2         Gdańsk  764.375875          Gdańsk
3         Kraków  886.776570          Kraków
4       Warszawa  299.196093        Warszawa
...          ...         ...             ...
499995   Wrocław  543.816961         Wrocław
499996   Wrocław  812.193989         Wrocław
499997   Wrocław   33.223412         Wrocław
499998    Poznań  761.822834          Poznań
499999    Kraków  955.474618          Kraków

[500000 rows x 3 columns]

In [9]:
df_duza.memory_usage(deep=True) / 1024

Index                 0.128906
Miasto             7518.833008
Wartosc            3906.250000
Miasto_category     488.357422
dtype: float64

In [10]:
df_duza.dtypes

Miasto                  str
Wartosc             float64
Miasto_category    category
dtype: object

In [ ]:
astype('int8')

In [11]:
df_duza.describe()

             Wartosc
count  500000.000000
mean      504.832713
std       285.422959
min        10.005230
25%       258.059314
50%       505.340170
75%       751.455693
max       999.997496

In [14]:
df_duza["Wartosc_float16"] = df_duza["Wartosc"].astype("float32")
df_duza.memory_usage(deep=True) / 1024

Index                 0.128906
Miasto             7518.833008
Wartosc            3906.250000
Miasto_category     488.357422
Wartosc_float16    1953.125000
dtype: float64

In [15]:
df_duza.describe()

             Wartosc  Wartosc_float16
count  500000.000000    500000.000000
mean      504.832713       504.832703
std       285.422959       285.422974
min        10.005230        10.005230
25%       258.059314       258.059303
50%       505.340170       505.340164
75%       751.455693       751.455673
max       999.997496       999.997498

In [19]:
for i, chunk in enumerate(pd.read_csv('spoleczenstwo.csv', chunksize=1000, sep="|")):
    print(i, chunk.shape)
    print(chunk.memory_usage())

0 (1000, 9)
Index           132
id             8000
imie          14371
nazwisko      14776
firma         30497
email         30515
telefon       21230
miasto        17337
ulica         17254
nr_budynku    11389
dtype: int64
1 (1000, 9)
Index           132
id             8000
imie          14324
nazwisko      14933
firma         30876
email         30332
telefon       21053
miasto        17106
ulica         17235
nr_budynku    11314
dtype: int64
2 (1000, 9)
Index           132
id             8000
imie          14341
nazwisko      14848
firma         30948
email         30325
telefon       21060
miasto        17479
ulica         17113
nr_budynku    11315
dtype: int64
3 (1000, 9)
Index           132
id             8000
imie          14340
nazwisko      15034
firma         30895
email         30309
telefon       21222
miasto        17319
ulica         17402
nr_budynku    11362
dtype: int64
4 (1000, 9)
Index           132
id             8000
imie          14398
nazwisko      14906
firma         30788
email         30471
telefon       21135
miasto        17348
ulica         17165
nr_budynku    11311
dtype: int64
5 (1000, 9)
Index           132
id             8000
imie          14366
nazwisko      14963
firma         31127
email         30421
telefon       21092
miasto        17363
ulica         17088
nr_budynku    11348
dtype: int64
6 (1000, 9)
Index           132
id             8000
imie          14347
nazwisko      15052
firma         31032
email         30317
telefon       21123
miasto        17457
ulica         17068
nr_budynku    11354
dtype: int64
7 (1000, 9)
Index           132
id             8000
imie          14432
nazwisko      15000
firma         30623
email         30379
telefon       21225
miasto        17306
ulica         17155
nr_budynku    11338
dtype: int64
8 (1000, 9)
Index           132
id             8000
imie          14438
nazwisko      14919
firma         30453
email         30371
telefon       21137
miasto        17464
ulica         17098
nr_budynku    11342
dtype: int64
9 (1000, 9)
Index           132
id             8000
imie          14370
nazwisko      14899
firma         30723
email         30409
telefon       21142
miasto        17184
ulica         17166
nr_budynku    11354
dtype: int64

In [21]:
df_full = pd.read_csv("spoleczenstwo.csv", sep="|")
df_full.memory_usage()

Index            132
id             80000
imie          143727
nazwisko      149330
firma         307962
email         303849
telefon       211419
miasto        173363
ulica         171744
nr_budynku    113427
dtype: int64

In [ ]:
df[df["kol"] == "wartosc"]

SyntaxError: invalid syntax (2267474731.py, line 1)

In [ ]:
df.where(F.col('kol') == 'wartość').select('geg', "eg" )